application: shotgun-mandrel
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /ami
  script: app/ami.py

- url: /_ah/mail/tix@.+
  script: app/mail.py
  login: admin

- url: /css
  static_dir: css

- url: /tasks/events
  script: tasks/events.py
  login: admin

- url: /admin/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: app/main.py
  login: required
